### ISSUE TITLE
Write your games in rust 

### ISSUE THREAD

**Issue by vijayksingh** [osynavets/build-your-own-x-in-rust#11]
Write your own Tetris : https://www.youtube.com/playlist?list=PLBNbqulT6FWw9C39_WIT_dcCIj1AdxiAy

More code your own games (Tetris, Minesweeper, Snake, Asterioids) : https://www.youtube.com/playlist?list=PLtTT8p-gjGEdGzZ0ET2bwNnA6iP_mmmrv

**Comment by durnosmih** [comment]
thanks for contribution. I added first one, not sure about those below
